### ISSUE TITLE
Привет)

### ISSUE THREAD

**Issue by pogudo-e** [AinurMingazov/aiogram_barber_bot#1]
Может поделитесь ссылочкой на какой нибудь там мануал по aiogram что б написать подобного бота)

**Comment by AinurMingazov** [comment]
Добрый день, конкретного одного мануала нет, нахожу у блоггеров что-нибудь
и добавляю или ищу по документации. Если интересует какой -то функционал
могу попробовать добавить.

вт, 23 янв. 2024 г., 01:14 pogudo-e ***@***.***>:
